import "./globals.css";
import SideNav from "@/components/SideNav";
import HeaderItems from "@/components/HeaderItems";
import { Inter } from "next/font/google";
import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await auth();

  return (
    <SessionProvider session={session}>
      <html lang="en">
        <body className={`font-sans ${inter.variable}`}>
          <div className="grid h-screen grid-cols-[16rem_1fr] grid-rows-[auto_1fr]">
            <header>
              <HeaderItems />
            </header>
            <aside className="row-span-full">
              <SideNav />
            </aside>
            <main className="p-9">
              <Toaster />
              {children}
            </main>
          </div>
        </body>
      </html>
    </SessionProvider>
  );
}
